# Generated by Django 4.2.6 on 2024-03-21 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtisAapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('frequency', models.CharField(max_length=2)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mtisAapp.user'),
        ),
        migrations.AddField(
            model_name='entrygroup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mtisAapp.user'),
        ),
        migrations.CreateModel(
            name='RelEGU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtisAapp.entry')),
                ('goal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mtisAapp.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtisAapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('weights', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtisAapp.weights')),
            ],
        ),
    ]
