# Generated by Django 4.2.6 on 2024-03-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtisAapp', '0002_goal_entry_user_entrygroup_user_relegu_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='encrypted_password',
            field=models.CharField(default='1234', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='1234', max_length=30),
        ),
    ]
