# Generated by Django 4.2.6 on 2024-03-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtisAapp', '0003_user_email_user_encrypted_password_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrygroup',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='character',
            field=models.CharField(default='Tommy', max_length=50),
        ),
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(default='Peaky Blinders', max_length=100),
        ),
        migrations.AlterField(
            model_name='goal',
            name='frequency',
            field=models.CharField(default='D', max_length=2),
        ),
    ]
