# Generated by Django 4.2.6 on 2024-03-22 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtisAapp', '0004_entrygroup_favorite_goal_favorite_story_character_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 19, 30, 25, 828280)),
        ),
    ]
