# Generated by Django 4.2.6 on 2024-03-23 12:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtisAapp', '0005_entry_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mtisAapp.entry'),
        ),
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mtisAapp.user'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 23, 13, 26, 25, 645814)),
        ),
        migrations.DeleteModel(
            name='RelEGU',
        ),
    ]
