# Generated by Django 4.2.6 on 2024-03-23 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtisAapp', '0007_user_name_alter_entry_datetime_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 23, 17, 58, 22, 92046)),
        ),
    ]
