# Generated by Django 4.2.6 on 2024-03-24 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtisAapp', '0008_alter_entry_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 24, 17, 23, 19, 990773)),
        ),
    ]
