# Generated by Django 4.2.6 on 2024-03-24 17:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtisAapp', '0009_alter_entry_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 24, 18, 25, 25, 281054)),
        ),
        migrations.AlterField(
            model_name='question',
            name='weights',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mtisAapp.weights'),
        ),
    ]
