# Generated by Django 4.2.6 on 2024-03-26 15:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtisAapp', '0010_alter_entry_datetime_alter_question_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entrygroup_child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_entrygroup', to='mtisAapp.entrygroup'),
        ),
        migrations.AddField(
            model_name='entry',
            name='entrygroup_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_entrygroup', to='mtisAapp.entrygroup'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 26, 16, 54, 7, 215210)),
        ),
    ]
