# Generated by Django 4.2.6 on 2024-03-26 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtisAapp', '0011_entry_entrygroup_child_entry_entrygroup_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='entrygroup_parent',
        ),
        migrations.AlterField(
            model_name='entry',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 0, 0)),
        ),
    ]
