# Generated by Django 4.2.6 on 2024-03-26 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtisAapp', '0012_remove_entry_entrygroup_parent_alter_entry_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_challenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mtisAapp.entry'),
        ),
    ]
