# Generated by Django 4.2.6 on 2024-03-26 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtisAapp', '0013_entry_entry_challenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entrygroup_child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mtisAapp.entrygroup'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Challenge',
        ),
    ]
